export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_SUCCESSFUL = 'SEND_ORDER_SUCCESSFUL';
export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED';
export const CLOSE_ORDER_POPUP = 'CLOSE_ORDER_POPUP';
