export const REGISTRTION_REQUEST: 'REGISTRTION_REQUEST' = 'REGISTRTION_REQUEST';
export const REGISTRTION_SUCCESSFUL: 'REGISTRTION_SUCCESSFUL' = 'REGISTRTION_SUCCESSFUL';
export const REGISTRTION_FAILED: 'REGISTRTION_FAILED' = 'REGISTRTION_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL' = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL' = 'LOGOUT_SUCCESSFUL';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const CHECK_TOKEN_REQUEST: 'CHECK_TOKEN_REQUEST' = 'CHECK_TOKEN_REQUEST';
export const CHECK_TOKEN_SUCCESSFUL: 'CHECK_TOKEN_SUCCESSFUL' = 'CHECK_TOKEN_SUCCESSFUL';
export const CHECK_TOKEN_UNSUCCESSFUL: 'CHECK_TOKEN_UNSUCCESSFUL' = 'CHECK_TOKEN_UNSUCCESSFUL';
export const CHECK_TOKEN_FAILED: 'CHECK_TOKEN_FAILED' = 'CHECK_TOKEN_FAILED';

export const UPDATE_REQUEST: 'UPDATE_REQUEST' = 'UPDATE_REQUEST';
export const UPDATE_SUCCESSFUL: 'UPDATE_SUCCESSFUL' = 'UPDATE_SUCCESSFUL';
export const UPDATE_FAILED: 'UPDATE_FAILED' = 'UPDATE_FAILED';
