export const SEND_REGISTRTION_REQUEST: 'SEND_REGISTRTION_REQUEST' = 'SEND_REGISTRTION_REQUEST';
export const REGISTRTION_SUCCESSED: 'REGISTRTION_SUCCESS' = 'REGISTRTION_SUCCESS';
export const REGISTRTION_FAILED: 'REGISTRTION_FAILED' = 'REGISTRTION_FAILED';

export const SEND_LOGIN_REQUEST: 'SEND_LOGIN_REQUEST' = 'SEND_LOGIN_REQUEST';
export const LOGIN_SUCCESSED: 'LOGIN_SUCCESSED' = 'LOGIN_SUCCESSED';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const SEND_LOGOUT_REQUEST: 'SEND_LOGOUT_REQUEST' = 'SEND_LOGOUT_REQUEST';
export const LOGOUT_SUCCESSED: 'LOGOUT_SUCCESSED' = 'LOGOUT_SUCCESSED';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const CHECK_TOKEN_REQUEST: 'CHECK_TOKEN_REQUEST' = 'CHECK_TOKEN_REQUEST';
export const CHECK_TOKEN_SUCCESSED: 'CHECK_TOKEN_SUCCESSED' = 'CHECK_TOKEN_SUCCESSED';
export const CHECK_TOKEN_UNSUCCESSED: 'CHECK_TOKEN_UNSUCCESSED' = 'CHECK_TOKEN_UNSUCCESSED';
export const CHECK_TOKEN_FAILED: 'CHECK_TOKEN_FAILED' = 'CHECK_TOKEN_FAILED';

export const SEND_UPDATE_REQUEST: 'SEND_UPDATE_REQUEST' = 'SEND_UPDATE_REQUEST';
export const UPDATE_SUCCESSED: 'UPDATE_SUCCESSED' = 'UPDATE_SUCCESSED';
export const UPDATE_FAILED: 'UPDATE_FAILED' = 'UPDATE_FAILED';
